export enum MatchMakingEvents {
    StartMatchmaking = 'startMatchmaking',
    SomeOneWaiting = 'someOneWaiting',
    LeaveWaitingRoom = 'leaveWaitingRoom',
    JoinRoom = 'joinRoom',
    AcceptOpponent = 'acceptOpponent',
    OpponentLeft = 'opponentLeft',
    RejectOpponent = 'rejectOpponent',
    OpponentJoined = 'opponentJoined',
    AcceptOtherPlayer = 'acceptOtherPlayer',
    RejectOtherPlayer = 'rejectOtherPlayer',
    RoomReachable = 'roomReachable',
    UpdateRoomView = 'updateRoomView',
    RoomCreatedForThisGame = 'roomCreatedForThisGame',
}
